id = "niva_lsp"
name = "niva"
description = "Niva lang support."
version = "0.0.2"
schema_version = 1
authors = ["gavr"]
repository = "https://github.com/gavr123456789/zed-niva"

[language_servers.niva]
name = "Niva Language Server"
languages = ["niva"]

[grammars.niva]
repository = "https://github.com/gavr123456789/tree-sitter-niva.git"
rev = "b0d8fa175706eba0cc29cc80b68cb2aaf3b61ddf"
